#################################################################
## This handles the loading of my automations
#################################################################   
automation: !include ../automations.yaml
automation split: !include_dir_list ../includes/automations