#################################################################
## This handles the loading of my sensors.
################################################################# 
sensor: !include_dir_merge_list ../includes/sensors