#################################################################
## This handles the loading of my sensors.
################################################################# 
sensor: !include  ../includes/sensors.yaml
sensor split: !include_dir_merged_list ../includes/sensors