#################################################################
## Home Assistant - Core Configuration
#################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#################################################################
## Components
#################################################################

# Recorder
recorder:
  auto_purge: true
  purge_keep_days: 5
  commit_interval: 1
  include:
    entities:
      - sensor.memory_use_percent
      - sensor.speedtest_download
      - sensor.speedtest_upload  
      - sensor.temperature_media  
      - sensor.time_online    
    entity_globs:
      - sensor.kirby_*
      - sensor.mail_*
      - sensor.processor_*    

# Text to speech
tts:
  - platform: google_translate

#################################################################
## Notifications
#################################################################

# Telegram bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids: !secret telegram_bot_chat_ids

# Notifications    
notify:
# Telegram
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_main_chat_id

#################################################################
## Software Integrations
#################################################################

# Google Cal
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret

# Speedtest
speedtestdotnet:
  scan_interval:
    hours: 2

#################################################################
## Device Integrations
#################################################################

# Dyson
dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: US
  devices:
    - device_id: !secret kirby_device_id
      device_ip: !secret kirby_device_ip

# Winston
vacuum:
  - platform: xiaomi_miio
    host: !secret winston_host
    token: !secret winston_token
    name: Winston

# NMAP Device Tracker
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.1/24

#################################################################
## Camera Integrations
#################################################################

camera:
# Winston lidar
  - platform: xiaomi_cloud_map_extractor
    host: !secret winston_host
    token: !secret winston_token
    username: !secret winston_username
    password: !secret winston_password
    country: us
    colors:
      color_map_outside: [3, 169, 244]
    room_colors: 
      # Hallway
      16: [253, 211, 82]
      # Living Room
      17: [106, 191, 209]
      # Kitchen
      18: [145, 200, 255]
      # Office
      19: [245, 142, 110]
      # Bathroom
      20: [7, 152, 183]
    draw: ["all"]
    map_transformation:
      scale: 2
      trim:
        top: 22
        bottom: 22
        left: 22
        right: 22
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true

#################################################################
## Media Players
#################################################################

media_player:
# Shield
  - platform: androidtv
    name: SHIELD TV
    host: !secret shield_ip
# Sonny
  - platform: androidtv
    name: Sonny TV
    host: !secret sonny_ip

#################################################################
## Sensors
#################################################################

sensor:
# Denon Receiver Volume Template Sensor
  - platform: template
    sensors:
      denon_volume:
        value_template: >
          {% if is_state('media_player.dennis', 'on')  %}
            {{ (state_attr('media_player.dennis', 'volume_level') * 100) | int }}
          {% endif %}
        friendly_name: Receiver Volume Level
        icon_template: mdi:volume-medium
# Google WiFi
#  - platform: google_wifi
# HA Component counts
  - platform: template
    sensors:
    # Count Automations 
      count_automations:
        entity_id: sensor.date
        value_template: "{{ states.automation | list | length }}"
        friendly_name: Automations   
        icon_template: mdi:abacus         
    # Count Binary Sensors
      count_binary_sensors:
        entity_id: sensor.date
        value_template: "{{ states.binary_sensor| list | length }}"
        friendly_name: Binary Sensors   
        icon_template: mdi:abacus    
    # Count Device Trackers
      count_device_trackers:
        entity_id: sensor.date
        value_template: "{{ states.device_tracker | list | length }}"
        friendly_name: Device Trackers   
        icon_template: mdi:abacus    
    # Count Scripts
      count_scripts:
        entity_id: sensor.date
        value_template: "{{ states.script| list | length }}"
        friendly_name: Scripts     
        icon_template: mdi:abacus    
    # Count Sensors
      count_sensors:
        entity_id: sensor.date
        value_template: "{{ states.sensor | list | length }}"
        friendly_name: Sensors    
        icon_template: mdi:abacus    
    # Count Switches
      count_switches:
        entity_id: sensor.date
        value_template: "{{ states.switch | list | length }}"
        friendly_name: Switches      
        icon_template: mdi:abacus            
# HA System Monitor
  - platform: systemmonitor 
    resources: 
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
# HA Uptime
  - platform: uptime
    name: Time Online
    unit_of_measurement: minutes  
# HA Latest Version
  - platform: version
    name: Latest Version
         
binary_sensor:
# Workday
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

#################################################################
## Switches
#################################################################

switch:
# Denon ECO Switch
  - platform: template
    switches:
      eco:
        friendly_name: "ECO Mode"
        turn_on:
          service: script.eco_on
        turn_off:
          service: script.eco_off
# Denon Menu Switch
  - platform: template
    switches:
      denon_menu:
        friendly_name: "Denon Menu"
        turn_on:
          service: script.av_menu_on
        turn_off:
          service: script.av_menu_off

######## INCLUDES ########
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest_command: !include rest_command.yaml
