#################################################################
## Home Assistant - Core Configuration
#################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#################################################################
## Theme
#################################################################

lovelace:
  mode: yaml
  resources:
    # Button Card
    # https://github.com/custom-cards/button-card
    - url: /hacsfiles/button-card/button-card.js                                  
      type: module
    # Card Mod
    # https://github.com/thomasloven/lovelace-card-mod
    - url: /hacsfiles/lovelace-card-mod/card-mod.js                               
      type: module
    # Custom Sidebar 
    # https://github.com/Villhellm/custom-sidebar
    - url: /hacsfiles/custom-sidebar/custom-sidebar.js                            
      type: module
    # Hui Element
    # https://github.com/thomasloven/lovelace-hui-element
    - url: /hacsfiles/lovelace-hui-element/hui-element.js                         
      type: module
    # Light Popup Card
    # https://github.com/DBuit/light-popup-card
    - url: /hacsfiles/light-popup-card/light-popup-card.js                        
      type: module
    # Lovelace Swipe Navigation
    # https://github.com/maykar/lovelace-swipe-navigation
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js               
      type: module       
    # Lovelace Xiaomi Vacuum Map card
    # https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js   
      type: module
    # Mini Graph Card
    # https://github.com/kalkih/mini-graph-card
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js                   
      type: module
    # RGB Light Card
    # https://github.com/bokub/rgb-light-card
    - url: /hacsfiles/rgb-light-card/card.js                                      
      type: module      
    # Paper Button Rows
    # https://github.com/jcwillox/lovelace-paper-buttons-row
    - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js             
      type: module
    # Slider Entity Row
    # https://github.com/thomasloven/lovelace-slider-entity-row
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js             
      type: module
    # Stack in Card
    # https://github.com/custom-cards/stack-in-card
    - url: /hacsfiles/stack-in-card/stack-in-card.js                              
      type: module  
    # State Switch
    # https://github.com/thomasloven/lovelace-state-switch
    - url: /hacsfiles/lovelace-state-switch/state-switch.js                       
      type: module
    # Vacuum Card
    # https://github.com/denysdovhan/vacuum-card
    - url: /hacsfiles/vacuum-card/vacuum-card.js                                  
      type: module
    # Vertical Stack in Card
    # https://github.com/ofekashery/vertical-stack-in-card
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js            
      type: module
    # Local Fonts
    - url: /local/font.css
      type: css
#################################################################
## Add-ons
#################################################################

browser_mod:
  prefix: "browser_mod_"
  devices:
    a314828b-6ae30387:
      name: "Lilt MacBook Pro"
    8fee92b6-03b9b09b:
      name: "Pixel 3"
  disable:
    - all

#################################################################
## Device Integrations
#################################################################

# AC
# frigidaire:
#   - platform: climate
#     username: !secret frigidaire_username
#     password: !secret frigidaire_password

# Winston
# vacuum:
#   - platform: xiaomi_miio
#     host: !secret winston_host
#     token: !secret winston_token
#     name: Winston

######## INCLUDES ########
homeassistant:
  packages: !include_dir_named integrations