# Downstairs Light Group
- platform: group
  name: Downstairs
  entities: 
    - group.overhead
    - group.track
    - light.dino_panel
    - light.hallway_runner
    - light.potter_lamp
    - light.kitchen
    - light.yumi_lamp
  icon: 'mdi:home-floor-g'
