#################################################################
## Alert Front Door
#
## Alert when front door is open 15+ seconds. 
#################################################################
alias: Alert Front Door
description: Alert when front door is open 10+ seconds.
trigger:
- type: opened
  platform: device
  device_id: a13166182e71a12ccc046137e74cde66
  entity_id: binary_sensor.front_door
  domain: binary_sensor
  for:
    hours: 0
    minutes: 0
    seconds: 10
    milliseconds: 0
condition: []
action:
- service: notify.telegram
  data:
    message: Front door is still open!
    title: '🚨 ALERT:'
mode: single