#################################################################
## Confirmation Door Closed
#
## Confirming door is closed.
#################################################################
alias: Confirmation Door Closed
description: Confirming door is closed.
trigger:
- type: not_opened
  platform: device
  device_id: a13166182e71a12ccc046137e74cde66
  entity_id: binary_sensor.front_door
  domain: binary_sensor
  for:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
condition: []
action:
- service: notify.telegram
  data:
    message: Front door is closed!
    title: '🚪 CONFIRMED:'
mode: single