#################################################################
## Denon Get Volume
#
## Display current volume of Denon AVR.
#################################################################
alias: Denon Get Volume
description: 'Display current volume of Denon AVR.'
trigger:
- platform: state
  entity_id: sensor.denon_volume
- platform: homeassistant
  event: start
condition:
- condition: state
  entity_id: media_player.dennis
  state: 'on'
action:
- delay:
    seconds: 3
- service: input_number.set_value
  data_template:
    entity_id: input_number.denon_volume
    value: '{{ trigger.to_state.state }}'
mode: restart
initial_state: 'on'