#################################################################
## Denon Set Volume
#
## Set volume of Denon AVR.
#################################################################
alias: Denon Set Volume
description: 'Set volume of Denon AVR.'
trigger:
- platform: state
	entity_id: input_number.denon_volume
condition: []
action:
- service: media_player.volume_set
	data_template:
	  entity_id: media_player.dennis
	  volume_level: '{{states(''input_number.denon_volume'') | int / 100}}

    '
mode: restart
initial_state: 'on'