#################################################################
## Office Available
#
## Turn Potter light to default color when work webcam turns off.
#################################################################
alias: "Office: Available"
description: ""
trigger:
  - type: turned_off
    platform: device
    device_id: 0d90cb630ecad3945965440c0dabc6cf
    entity_id: binary_sensor.jeffreys_macbook_pro_camera_in_use
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
condition: []
action:
  - scene: scene.office_available
mode: single
