#################################################################
## Kettle Shutoff
#
## Shutoff plug to kettle 15-minutes after device has been switched on.
#################################################################
alias: Shutoff Kettle
description: Shutoff plug to kettle 15-minutes after device has been switched on.
trigger:
- platform: state
  for: 00:15:00
  from: 'off'
  to: 'on'
  entity_id: switch.kettle
action:
- type: turn_off
  device_id: cc9c28d8ff6a11ea876cbbcc11d5e81d
  entity_id: switch.kettle
  domain: switch
mode: single