#################################################################
## Vacuum Done
#
## Notify Farnsworth when Winston has completed cleaning.
#################################################################
alias: Vacuum Done
description: Notify Farnsworth when Winston has completed cleaning.
trigger:
- platform: state
  entity_id: vacuum.winston
  from: cleaning
  to: returning
condition: []
action:
- service: notify.telegram
  data:
    message: I've completed cleaning the residence. I'm off to retire. Cheerio!
    title: '🤹🏻‍ Winston:'
mode: single