#################################################################
## Switchbot for heater.
#################################################################
- platform: switchbot
  mac: !secret switchbot_mac  