blueprint:
  name: Shutoff timer
  description: Shutoff device after it has be on for a defined interval.
  domain: automation

  input:
    trigger_device:
      name: Device
      description: Which device to monitor and toggle?
      selector:
        entity:
    duration:
      name: Duration
      description: What period to wait before toggling state? (HH:MM:SS)   

trigger:
  platform: state
  entity_id: !input trigger_device
  for: !input duration
  from: 'off'
  to: 'on'

action: 
  type: turn_off
  entity_id: !input trigger_device