#################################################################
## Steam Integration
################################################################# 
- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - !secret steam_id