
#################################################################
## Global
#################################################################
# Downstairs Light Group
- platform: group
  name: Downstairs
  entities: 
    - light.overhead
    - light.track
    - light.dino_panel
    - light.hallway_runner
    - light.potter_lamp
    - light.kitchen
    - light.yumi_lamp
# Upstairs Light Group
- platform: group
  name: Upstairs
  entities: 
    - light.loft 
    - light.hallway_marquee
    - light.stair
#################################################################
## Loft
#################################################################
# Bedside Light Group
- platform: group
  name: Bedside
  entities:
    - light.jeffreys_lamp
    - light.tiffanys_lamp
#################################################################
## Office
#################################################################
# Office Light Group
- platform: group
  name: Overhead
  entities:
    - light.overhead_bed
    - light.overhead_desk
#################################################################
## Living Room
#################################################################
# Track Lighting
- platform: group
  name: Track
  entities:
    - light.left_track
    - light.center_track
    - light.right_track